spring.application.name=teste


# Dados de conexão com o banco H2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=lynx
spring.datasource.password=

# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.sql.init.mode=always

# H2 Client
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create


# --- Configuração SQLite ---

; # Onde o arquivo será salvo (na raiz do projeto com nome 'database.db')
; #  spring.datasource.url=jdbc:sqlite:./database.db
; spring.datasource.url=jdbc:sqlite:data/database.db
; spring.datasource.driver-class-name=org.sqlite.JDBC
; spring.datasource.username=lynx
; spring.datasource.password=
;
; # --- Configuração do Hibernate/JPA ---
;
; # Define o Dialeto Comunitário (Essa linha é a chave do sucesso)
; spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
;
; # Tenta atualizar o banco se a entidade mudar (Cuidado: SQLite é ruim com 'update')
; spring.jpa.hibernate.ddl-auto=update
;
; # Mostra o SQL no console para você debugar
; spring.jpa.show-sql=true
;
;




